# Generated by Django 3.0.5 on 2020-04-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
    ]
