# Generated by Django 3.0.5 on 2020-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0002_auto_20200420_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
