# Generated by Django 3.0.5 on 2020-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_auto_20200421_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='human_avatar/'),
        ),
    ]
